sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

env:
  - CODECLIMATE_REPO_TOKEN=fa4c7a699042fb2632cca5b0535edebb32939fa04462f2cde0cef928667e338a

before_script:
  - 'npm install -g gulp bower && cd public && bower install && cd ..'

after_success:
  - npm run-script coverage-upload
